server:
  port: 28080
jwt:
  secret: gx4SN/4gh6QPvLfVWCW8Aoo4l2n66d2338IwXyu1koDT1W94XS35OZJPYkA2IIMMgmlz96LCHSNc8jLYuzwB1IreKOZz2TZhsWODfjHAS9bYlduniCUSuSPZ5/OP15O63fn1kN1N5w64frpyWcWbTtiCgLMkJpnfjmqFMAr7fgcOGyt2rmunvFYni9T78Q4fn/0gpx3qm8zXw3oBbFb1Ge9Wnh1UCSapXd/EzLau3iaXqp9f+8FHmSCo9vbEaRSRMPHdcpnB4WKHKySE/BCNSsWM+kHmHyrAbvKErPCz2XXMnIalUoAtquq03LnmYjrBHyI230VcYEVzGmzLOTsSJw==
  access_token:
    expiration: 36000
  refresh_token:
    expiration: 604800
spring:
  # Mysql 配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/敏捷开发
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456  #(如果有密码的话)

<<<<<<< HEAD
# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
    secret: gx4SN/4gh6QPvLfVWCW8Aoo4l2n66d2338IwXyu1koDT1W94XS35OZJPYkA2IIMMgmlz96LCHSNc8jLYuzwB1IreKOZz2TZhsWODfjHAS9bYlduniCUSuSPZ5/OP15O63fn1kN1N5w64frpyWcWbTtiCgLMkJpnfjmqFMAr7fgcOGyt2rmunvFYni9T78Q4fn/0gpx3qm8zXw3oBbFb1Ge9Wnh1UCSapXd/EzLau3iaXqp9f+8FHmSCo9vbEaRSRMPHdcpnB4WKHKySE/BCNSsWM+kHmHyrAbvKErPCz2XXMnIalUoAtquq03LnmYjrBHyI230VcYEVzGmzLOTsSJw==
    access_token:
      expiration: 3600
    refresh_token:
      expiration: 604800
=======
  # session 配置
  session:
    store-type: redis
>>>>>>> bd1f16a0259d42b726a0fcaa25545675da38a207
